### ISSUE TITLE
Token Leaked

### ISSUE THREAD

**Issue by EJH2** [Apticode/hermes.py#1]
https://github.com/Ghostpowerz/hermes.py/blob/3698d3f0078153134cbe04809aaa344d5622e43c/hermes.py#L146

**Comment by jenkk** [comment]
Well spotted, completely passed us by.  

Apologies for the late reply as for some reason I don't get notifications from this repository.
If you happen to have any contributions you would like to make or would like to help both our project and the bot I see yourself working on then feel free to holla.  
Last time I checked we were figuring out cogs so it'd be pretty sweet if you could lend a hand 👍   
  
/issue
